apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  # replicas: 5 
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers: 
        - name: api-conversao
          image: amandhaasil/api-conversao:v1
          ports:
            - containerPort: 8080
          livenessProbe: # NEW CONFIG -> self healing 
            httpGet:
              path: /health
              port: 8080

