apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers: 
        - name: api-conversao
          image: amandhaasil/api-conversao:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2 # Para começar a bater no health
            periodSeconds: 2 # De quanto em quanto vou verificar a saude
            timeoutSeconds: 1 # quanto tempo espera pela resposta
            successThreshold: 1 # quantos sucessos precisam acontecer pra eu considerar que ta healthy de novo?
            failureThreshold: 1 # quantas falhas pra eu considerar que ta unhealthy e precisa dar restart na aplicação?
          readinessProbe: # NEW CONFIG
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2 # Para começar a bater no health
            periodSeconds: 2 # De quanto em quanto vou verificar a saude
            timeoutSeconds: 1 # quanto tempo espera pela resposta
            successThreshold: 1 # quantos sucessos precisam acontecer pra eu considerar que ta healthy de novo?
            failureThreshold: 1 # quantas falhas pra eu considerar que ta unhealthy e precisa dar restart na aplicação?
