apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 80 # porta do pod
      targetPort: 8080 # porta do container
      nodePort: 30000 # porta do serviço
  type: NodePort
